extends Node2D

@export_file("*.tscn") var wrong_building: String
@export_file("*.tscn") var next_level: String

@export var base_mode: GUIDEMappingContext


# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	GUIDE.enable_mapping_context(base_mode)


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta: float) -> void:
	pass
	
	
func _on_door_event_triggered(event_id: String) -> void:
	if event_id == "right":
		SceneLoader.load_scene(next_level)
		return
		 
	SceneLoader.load_scene(wrong_building)
