extends Node2D

@export_file("*.tscn") var golé: String
@export_file("*.tscn") var next_level: String

@export var base_mode: GUIDEMappingContext

@export var vies = 3


# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	GUIDE.enable_mapping_context(base_mode)


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta: float) -> void:
	pass
	
	
func _on_interactible_triggered(event_id: String) -> void:
	vies -= 1
	if vies == 0:
		SceneLoader.load_scene(golé)


func _on_wrong_door_event_triggered(event_id: String) -> void:
	SceneLoader.load_scene(golé)


func _on_right_door_event_triggered(event_id: String) -> void:
	SceneLoader.load_scene(next_level) # Replace with function body.
